playlist-app/config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  devise_for :users

  root "playlists#index"
end

playlist-app/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user

  validates :name, :description, presence: true
end

playlist-app/app/models/product.rb
class Product < ActiveRecord::Base
end

playlist-app/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable

  has_many :playlists
end

playlist-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

playlist-app/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = if current_user.admin?
      Playlist.all
    else
      current_user.playlists
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :description)
    end
end

playlist-app/app/helpers/application_helper.rb
module ApplicationHelper
end

playlist-app/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

playlist-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaylistApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

playlist-app/app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

playlist-app/app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

playlist-app/app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin? %>
  <h1>Hello Admin!</h1>
<% else %>
  <h1>Hello User!</h1>
<% end %>

<h2>Listing Playlists</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.description %></td>
        <td><%= link_to 'Show', playlist %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
          <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

playlist-app/app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

playlist-app/app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @playlist.description %>
</p>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_playlist_path(@playlist) %>
<% end %>

<%= link_to 'Back', playlists_path %>